### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by MartinKolarik** [jsdelivr/globalping-dash-directus#27]
Either fully automated like with GP API, or a test suite that targets the configured directus URL (that I launch myself).

**Comment by alexey-yarmosh** [comment]
I think it should test combination of globalping-dash-directus and globalping-dash, by clicking the UI using e.g. Playwright. Pretty similar to the GP api + GP probe. Tests then may be executed in both dash repos.

**Comment by MartinKolarik** [comment]
That's an option as well, but UI tests are generally much slower to run and more fragile, I'd be fine with just testing the API too.

**Comment by MartinKolarik** [comment]
It was broken once because of missing extensions, which these tests would catch, and then because of URL change, which they would catch as well (yes, it's possible we'd still forget to update dash, but if you had to change an e2e test in the PR here, it would be much more obvious the dash needs an update too). I'm fine with both options though.
